version: '3'

services:
    db:
        image: postgres
    web:
        build:
            context: ../../
            dockerfile: docker/Dockerfile/dev
        env_file:
            - ../../.env
        volumes:
            - ../../:/app/
        ports:
            - "8000:8000"
        entrypoint: /app/docker/docker-entrypoint/dev.sh
        depends_on:
            - db
